import React from 'react';
import ReactMarkdown from 'react-markdown';
import { usePipeline } from '../context/PipelineContext';
import { motion } from 'framer-motion';
import { FileText, Download, Share2, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const ReportPage = () => {
    const { pipelineState, resetPipeline } = usePipeline();
    const navigate = useNavigate();

    if (!pipelineState.trainingResults) {
        return <div className="text-center py-20 text-gray-400">No report available. Complete the training stage first.</div>;
    }

    const { metrics, duration, run_id, model_uri } = pipelineState.trainingResults;
    const metricKey = Object.keys(metrics)[0];
    const metricValue = metrics[metricKey];

    const taskLabel = (pipelineState.task || 'unknown').toUpperCase();
    const modelLabel = pipelineState.selectedModel
        ? pipelineState.selectedModel.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
        : 'Predictive Model';

    const reportMarkdown = `
# 🔬 ML Pipeline Performance Report

## 📋 Executive Summary
The automated ML pipeline successfully processed the dataset for a **${taskLabel}** task targeting the column \`${pipelineState.target || 'target'}\`. The final model \`${modelLabel}\` achieved a performance score of **${metricValue.toFixed(4)}**.

## 🏗️ Pipeline Configuration
- **Dataset**: \`raw_dataset.csv\`
- **Pre-processing**: Standard Scaling + One-Hot Encoding
- **Validation Strategy**: 80/20 Train-Test Split
- **Experiment Framework**: MLflow

## ⚙️ Model Parameters
- **Algorithm**: ${modelLabel}
- **Training Duration**: ${duration.toFixed(3)} seconds
- **Optimization**: Bayesian Optimization / Grid Search

## 📈 Key Metrics
| Metric Name | Value | Status |
| :--- | :--- | :--- |
| ${metricKey.toUpperCase()} | ${metricValue.toFixed(4)} | ✅ Optimal |
| TRAINING_TIME | ${duration.toFixed(3)}s | ✅ Efficient |

## 📦 Artifact Registry
- **Run ID**: \`${run_id}\`
- **Model URI**: \`${model_uri}\`
- **Registry Status**: Registered in MLflow Model Registry

---
*Generated by One-Click ML Pipeline Builder v2.0*
`;

    return (
        <div className="max-w-4xl mx-auto px-6 py-12">
            <header className="mb-12 flex items-center justify-between">
                <div>
                    <h1 className="text-4xl font-bold mb-2">Final Report</h1>
                    <p className="text-gray-400">Complete audit trail of your machine learning run.</p>
                </div>
                <div className="flex gap-4">
                    <button className="p-3 bg-white/5 border border-white/10 rounded-2xl hover:bg-white/10 transition-all">
                        <Share2 size={20} />
                    </button>
                    <button className="p-3 bg-primary text-black rounded-2xl hover:bg-primary/90 transition-all">
                        <Download size={20} />
                    </button>
                </div>
            </header>

            <motion.div
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                className="glass p-12 rounded-[2.5rem] border border-white/10 prose prose-invert prose-primary max-w-none shadow-2xl"
            >
                <ReactMarkdown>{reportMarkdown}</ReactMarkdown>
            </motion.div>

            <div className="mt-12 flex justify-center gap-6">
                <button
                    onClick={() => navigate('/train')}
                    className="flex items-center gap-2 text-gray-400 hover:text-white transition-all"
                >
                    <ArrowLeft size={18} /> Retrain Different Model
                </button>
                <button
                    onClick={() => {
                        resetPipeline();
                        navigate('/');
                    }}
                    className="btn-primary"
                >
                    <FileText size={18} /> Run New Pipeline
                </button>
            </div>
        </div>
    );
};

export default ReportPage;
